SQL_SERVER="svd-nps-gauge.database.windows.net"
SQL_DB="free-sql-db-nps-gauge"
SQL_USER="app_user"
SQL_PASSWORD="AdminG@uge280"

N8N_FORCE_URL="https://sai-marketing.app.n8n.cloud/webhook/10e983d1-9edb-459e-b6af-dc8950a8172b"

ENV="local"